# Configuración optimizada para Netlify

[build]
  publish = "."
  command = "echo 'No build needed'"

[build.environment]
  NODE_VERSION = "18"

# Optimizaciones
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirecciones
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "https://intranet.reyesia.com/*"
  to = "/intranet-login.html"
  status = 200
