# Configuración optimizada para Netlify con backend

[build]
  publish = "."
  command = "echo 'No build needed'"

# Variables de entorno para producción
[build.environment]
  NODE_VERSION = "18"
  JWT_SECRET = "reyesia-production-jwt-secret-2024"
  SUPABASE_URL = "https://ttmtnsyogyldmmxxjjpz.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0bXRuc3lvZ3lsZG1teHhqanB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTc5ODcsImV4cCI6MjA3Mzg3Mzk4N30.imoJX22VH_8ntl5VG-IEdEKeIecC5u6ZkhgIhFLWDzg"

# Optimizaciones
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Cache para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Cache para PDFs
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirecciones para el backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/intranet-login.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[redirects]]
  from = "https://intranet.reyesia.com/*"
  to = "/intranet-login.html"
  status = 200
